<a href="https://colab.research.google.com/github/Shubhbhangoo/Shubhbhangoo/blob/main/ridge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn


In [ ]:
df=pd.read_csv('/content/bangalore house price prediction OHE-data 2.csv')

In [ ]:
df

bath  balcony   price  total_sqft_int  bhk  price_per_sqft  \
0      3.0      2.0  150.00          1672.0    3     8971.291866   
1      3.0      3.0  149.00          1750.0    3     8514.285714   
2      3.0      2.0  150.00          1750.0    3     8571.428571   
3      2.0      2.0   40.00          1250.0    2     3200.000000   
4      2.0      2.0   83.00          1200.0    2     6916.666667   
...    ...      ...     ...             ...  ...             ...   
7115   3.0      2.0  325.00          2900.0    3    11206.896552   
7116   3.0      1.0   84.83          1780.0    3     4765.730337   
7117   2.0      1.0   48.00           880.0    2     5454.545455   
7118   2.0      1.0   55.00          1000.0    2     5500.000000   
7119   2.0      1.0   78.00          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                                 1                        0   
1                                 0                        1   
2                                 1                        0   
3                                 1                        0   
4                                 0                        0   
...                             ...                      ...   
7115                              1                        0   
7116                              1                        0   
7117                              0                        0   
7118                              0                        0   
7119                              0                        0   

      area_typePlot  Area  availability_Ready To Move  ...  \
0                       0                           1  ...   
1                       0                           1  ...   
2                       0                           1  ...   
3                       0                           1  ...   
4                       1                           1  ...   
...                   ...                         ...  ...   
7115                    0                           1  ...   
7116                    0                           0  ...   
7117                    1                           1  ...   
7118                    1                           0  ...   
7119                    1                           0  ...   

      location_Kalena Agrahara  location_Horamavu Agara  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   
...                        ...                      ...   
7115                         0                        0   
7116                         0                        0   
7117                         0                        0   
7118                         0                        0   
7119                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
0                           0                       0   
1                           0                       0   
2                           0                       0   
3                           0                       0   
4                           0                       0   
...                       ...                     ...   
7115                        0                       0   
7116                        0                       0   
7117                        0                       0   
7118                        0                       0   
7119                        0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
0                             0                    0   
1                             0                    0   
2                             0                    0   
3                             0                    0   
4

deleting excess columns

In [ ]:
df=df[['bath','balcony','price','total_sqft_int','bhk','price_per_sqft','area_typeSuper built-up  Area','area_typeBuilt-up  Area','area_typePlot  Area','availability_Ready To Move']] # Use a tab character (\t) in the column name

In [ ]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  
0                    0                           1  
1                    0                           1  
2                    0                           1  
3                    0                           1  
4                    1                           1

In [ ]:
df

bath  balcony   price  total_sqft_int  bhk  price_per_sqft  \
0      3.0      2.0  150.00          1672.0    3     8971.291866   
1      3.0      3.0  149.00          1750.0    3     8514.285714   
2      3.0      2.0  150.00          1750.0    3     8571.428571   
3      2.0      2.0   40.00          1250.0    2     3200.000000   
4      2.0      2.0   83.00          1200.0    2     6916.666667   
...    ...      ...     ...             ...  ...             ...   
7115   3.0      2.0  325.00          2900.0    3    11206.896552   
7116   3.0      1.0   84.83          1780.0    3     4765.730337   
7117   2.0      1.0   48.00           880.0    2     5454.545455   
7118   2.0      1.0   55.00          1000.0    2     5500.000000   
7119   2.0      1.0   78.00          1400.0    3     5571.428571   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                                 1                        0   
1                                 0                        1   
2                                 1                        0   
3                                 1                        0   
4                                 0                        0   
...                             ...                      ...   
7115                              1                        0   
7116                              1                        0   
7117                              0                        0   
7118                              0                        0   
7119                              0                        0   

      area_typePlot  Area  availability_Ready To Move  
0                       0                           1  
1                       0                           1  
2                       0                           1  
3                       0                           1  
4                       1                           1  
...                   ...                         ...  
7115                    0                           1  
7116                    0                           0  
7117                    1                           1  
7118                    1                           0  
7119                    1                           0  

[7120 rows x 10 columns]

In [ ]:
x=df.drop('price',axis=1)
y=df['price']


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)



In [ ]:
x

array([[ 0.69474992,  0.55447784,  0.21042674, ..., -0.4721731 ,
        -0.25695885,  0.51138699],
       [ 0.69474992,  1.85228824,  0.29579247, ...,  2.11786735,
        -0.25695885,  0.51138699],
       [ 0.69474992,  0.55447784,  0.29579247, ..., -0.4721731 ,
        -0.25695885,  0.51138699],
       ...,
       [-0.44581255, -0.74333255, -0.65636376, ..., -0.4721731 ,
         3.89167377,  0.51138699],
       [-0.44581255, -0.74333255, -0.52503187, ..., -0.4721731 ,
         3.89167377, -1.95546625],
       [-0.44581255, -0.74333255, -0.08725889, ..., -0.4721731 ,
         3.89167377, -1.95546625]])

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x=poly.fit_transform(x)

In [ ]:
x

array([[ 1.        ,  0.69474992,  0.55447784, ...,  0.06602785,
        -0.13140541,  0.26151665],
       [ 1.        ,  0.69474992,  1.85228824, ...,  0.06602785,
        -0.13140541,  0.26151665],
       [ 1.        ,  0.69474992,  0.55447784, ...,  0.06602785,
        -0.13140541,  0.26151665],
       ...,
       [ 1.        , -0.44581255, -0.74333255, ..., 15.14512472,
         1.99015134,  0.26151665],
       [ 1.        , -0.44581255, -0.74333255, ..., 15.14512472,
        -7.61003669,  3.82384824],
       [ 1.        , -0.44581255, -0.74333255, ..., 15.14512472,
        -7.61003669,  3.82384824]])

Ridge model

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.linear_model import Ridge
model=Ridge()
model.fit(x_train,y_train)


Ridge()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred

array([ 67.96535459,  36.00613937,  61.03617018, ...,  90.02668765,
        74.99744857, 863.89418729])

In [ ]:
y_test

1189     68.0
5876     36.0
5597     61.0
3391     85.0
6122     64.0
        ...  
5830    187.0
4887     57.0
1861     90.0
3014     75.0
1670    864.0
Name: price, Length: 1424, dtype: float64

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9999999147162086

linear regression

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_predict=lr.predict(x_test)

In [ ]:
y_predict

array([ 68.,  36.,  61., ...,  90.,  75., 864.])

In [ ]:
r2_score(y_test,y_predict)

1.0